/**
 * Shared sidebar declarations.
 *
 * Both the Astro/Starlight config (`scripts/astro-config.ts`) and the standalone sidebar document
 * (`src/pages/sidebar.astro`) build their navigation from these, so the two never drift apart.
 * The API portion of the tree is not declared here — it comes from `src/generated-sidebar.json`,
 * written by `scripts/generate-api-docs.ts`.
 */

export interface AutogeneratedGroupSpec {
  /**
   * Directory under `src/content/docs` whose pages make up the group.
   */
  directory: string;
  label: string;
}

export interface SidebarLinkSpec {
  label: string;
  link: string;
}

/**
 * A container of further entries. An empty `items` array marks a visual separator rather than a
 * navigable group — `generate-api-docs.ts` emits one between the `obsidian` package and the
 * third-party packages.
 */
export interface SidebarTreeGroup {
  collapsed?: boolean;
  items: SidebarTreeNode[];
  label: string;
}

export interface SidebarTreeLink {
  label: string;
  /**
   * Root-relative and WITHOUT the site base path, matching what Starlight's own sidebar config
   * takes. Renderers prepend `import.meta.env.BASE_URL` themselves.
   */
  link: string;
}

export type SidebarTreeNode = SidebarTreeGroup | SidebarTreeLink;

export function isSidebarTreeGroup(node: SidebarTreeNode): node is SidebarTreeGroup {
  return 'items' in node;
}

export const AUTOGENERATED_GROUPS: AutogeneratedGroupSpec[] = [
  { directory: 'guides', label: 'Guides' },
  { directory: 'resources', label: 'Resources' }
];

export const START_HERE_GROUP_LABEL = 'Start Here';

export const START_HERE_LINKS: SidebarLinkSpec[] = [
  { label: 'Getting Started', link: '/getting-started/' },
  { label: 'Usage', link: '/usage/' },
  { label: 'Disclaimer', link: '/disclaimer/' },
  { label: 'Contributing', link: '/contributing/' },
  { label: 'Attribution', link: '/attribution/' }
];
